Vagrant.configure("2") do |config|

  config.vbguest.auto_update = false

  config.vm.define "centos_server_test" do |server|
    server.vm.box = "centos/7"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "centos.server.test.local"
      vb.memory = 2048
      vb.cpus = 1
    end
  end
  
  config.vm.network "forwarded_port", guest: 80, host: 8080
  
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbooks/run.yml"
    ansible.tags = "healthchecks"
  end

end

