Vagrant.configure("2") do |config|

  config.vbguest.auto_update = true

  config.vm.define "centos_server" do |server|
    server.vm.box = "centos/7"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "centos.server.local"
      vb.memory = 2048
      vb.cpus = 1
    end
  end
  
  config.vm.synced_folder "../userapi/", "/home/vagrant/userapi", type:"virtualbox", create: true  
  
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbooks/main.yml"
  end

end

