apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-userapi
  labels:
    app: kubernetes-userapi
spec:
  # TO COMPLETE #2
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-userapi
  template:
    metadata:
      labels:
        app: kubernetes-userapi
    spec:
      containers:
      - name: userapi
      # TO COMPLETE #1
        image: etiennectc/userapi
    
