Vagrant.configure("2") do |config|

  config.vbguest.auto_update = true

  config.vm.define "centos_server" do |server|
    server.vm.box = "centos/7"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "centos.server.local"
      vb.memory = 2048
      vb.cpus = 1
    end
  end
  
  config.vm.synced_folder "~/DevOpsECE2022/userapi", "/vagrant", type:"virtualbox"  

end

